name: "Deploy Azure services via Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_AZUREAD: true

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform init
        shell: bash
        working-directory: ./infrastructure/terraform/environments/test
        run: terraform init
      
      - name: Terraform validate
        shell: bash
        working-directory: ./infrastructure/terraform/environments/test
        run: terraform validate
      
      - name: Terraform plan
        shell: bash
        working-directory: ./infrastructure/terraform/environments/test
        run: terraform plan -out=tfplan

      - name: Terraform apply
        shell: bash
        working-directory: ./infrastructure/terraform/environments/test
        run: terraform apply tfplan -auto-approve